# Generated by Django 4.2.5 on 2023-10-05 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GelatoParadiso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Helado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='helados/')),
            ],
        ),
        migrations.CreateModel(
            name='Pastel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='pasteles/')),
            ],
        ),
    ]
