# Generated by Django 4.2.5 on 2023-10-05 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GelatoParadiso', '0002_helado_pastel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helado',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='pastel',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='helado',
            name='descripcion_corta',
            field=models.TextField(default='Descripción por defecto corta'),
        ),
        migrations.AddField(
            model_name='helado',
            name='descripcion_larga',
            field=models.TextField(default='Descripción por defecto'),
        ),
        migrations.AddField(
            model_name='pastel',
            name='descripcion_larga',
            field=models.TextField(default='Descripción por defecto'),
        ),
    ]
