# Generated by Django 4.2.5 on 2023-10-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GelatoParadiso', '0003_remove_helado_descripcion_remove_pastel_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion_larga', models.TextField(default='Descripción por defecto')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='pasteles/')),
            ],
        ),
        migrations.CreateModel(
            name='Infantil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion_larga', models.TextField(default='Descripción por defecto')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='pasteles/')),
            ],
        ),
    ]
