# Generated by Django 4.2.5 on 2023-10-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GelatoParadiso', '0004_batido_infantil'),
    ]

    operations = [
        migrations.AddField(
            model_name='batido',
            name='descripcion_corta',
            field=models.TextField(default='Descripción por defecto corta'),
        ),
        migrations.AddField(
            model_name='infantil',
            name='descripcion_corta',
            field=models.TextField(default='Descripción por defecto corta'),
        ),
        migrations.AddField(
            model_name='pastel',
            name='descripcion_corta',
            field=models.TextField(default='Descripción por defecto corta'),
        ),
    ]
