# Generated by Django 4.2.5 on 2023-10-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GelatoParadiso', '0005_batido_descripcion_corta_infantil_descripcion_corta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batido',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='batidos/'),
        ),
        migrations.AlterField(
            model_name='infantil',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='infantil/'),
        ),
    ]
